export const LAND_USE_OPTIONS = {
  "Field crops": [
    { code: "WHEAT", label: "Wheat" },
    { code: "PADDY", label: "Paddy / Rice" },
    { code: "MAIZE", label: "Maize" },
    { code: "SMALL_MILLETS", label: "Small millets" },
    { code: "PULSES", label: "Pulses" },
    { code: "OILSEEDS", label: "Oilseeds" },
    { code: "COARSE_GRAINS", label: "Coarse grains" },
    { code: "OATS", label: "Oats" },
    { code: "BARLEY", label: "Barley" },
    { code: "COVER_CROP", label: "Cover crop" },
  ],
  "Horticulture": [
    { code: "ROOT_CROPS", label: "Root crops" },
    { code: "VEGETABLES", label: "Vegetables" },
    { code: "POTATO", label: "Potato" },
    { code: "TAPIOCA", label: "Tapioca" },
    { code: "GINGER", label: "Ginger" },
    { code: "TURMERIC", label: "Turmeric" },
    { code: "PAPAYA", label: "Papaya" },
    { code: "BANANA", label: "Banana" },
  ],
  "Plantation and spices": [
    { code: "TEA", label: "Tea" },
    { code: "COFFEE", label: "Coffee" },
    { code: "ARECANUT", label: "Arecanut" },
    { code: "COCONUT", label: "Coconut" },
    { code: "BLACK_PEPPER", label: "Black pepper" },
    { code: "NUTMEG", label: "Nutmeg" },
    { code: "CINNAMON", label: "Cinnamon" },
    { code: "SPICES", label: "Mixed spices" },
  ],
  "Non-arable check": [
    { code: "BARREN_LAND", label: "Barren land" },
    { code: "BARE_GROUND", label: "Bare ground" },
    { code: "FOREST", label: "Forest / trees" },
    { code: "BUILT_UP", label: "Built-up / urban" },
    { code: "WATERBODY", label: "Waterbody" },
  ],
};
